[[redirects]]
from = "/api-reference"
to = "/docs/get-started"
status = 301

[[redirects]]
from = "/docs"
to = "/docs/get-started"
status = 301

[[redirects]]
from = "/docs/getting-started/change-log"
to = "/docs/migration-guides/from-automock"
status = 301

# Google Search Console 404s (Nov 2025)
[[redirects]]
from = "/docs/overview/examples"
to = "/docs/get-started/quickstart"
status = 301

[[redirects]]
from = "/docs/extras/identical-injections"
to = "/docs/guides/adapters/identifiers"
status = 301

[[redirects]]
from = "/docs/category/di-framework-adapters"
to = "/docs/guides/adapters"
status = 301

# High-traffic redirects (from analytics)
[[redirects]]
from = "/docs/overview/quickstart"
to = "/docs/get-started/quickstart"
status = 301

[[redirects]]
from = "/docs/overview/installation"
to = "/docs/get-started/installation"
status = 301

[[redirects]]
from = "/docs/developer-guide/unit-tests/suites-api"
to = "/docs/api-reference"
status = 301

[[redirects]]
from = "/docs/developer-guide/unit-tests/solitary"
to = "/docs/guides/solitary"
status = 301

[[redirects]]
from = "/docs/developer-guide/unit-tests/sociable"
to = "/docs/guides/sociable"
status = 301

[[redirects]]
from = "/docs/overview/problems-solved"
to = "/docs/get-started/why-suites"
status = 301
