[[redirects]]
from = "/api-reference"
to = "/docs/get-started"
status = 301

[[redirects]]
from = "/docs"
to = "/docs/get-started"
status = 301

[[redirects]]
from = "/docs/getting-started/change-log"
to = "/docs/migration-guides/from-automock"
status = 301
